# -*- coding: utf-8 -*-
"""download_images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_F0bTmxe3giOSnkFucAkOtSQNQ1gmXcL
"""

import os
import urllib.request
from serpapi import GoogleSearch

API_KEY = "11b476d191f6b996c28b37550b6bf54fa3021eabc31abfb496034b793902e788"

characters = [
    "Tyrion Lannister", "Cersei Lannister", "Jon Snow", "Daenerys Targaryen",
    "Jaime Lannister", "Arya Stark", "Sansa Stark", "Bran Stark", "Jorah Mormont",
    "Theon Greyjoy", "Samwell Tarly", "Petyr Baelish", "Brienne of Tarth",
    "Varys", "Davos Seaworth", "Stannis Baratheon", "Sandor Clegane",
    "Joffrey Baratheon", "Robb Stark", "Melisandre", "Gendry", "Missandei",
    "Grey Worm", "Ramsay Bolton", "Tormund Giantsbane"
]

output_dir = "images"
os.makedirs(output_dir, exist_ok=True)

def sanitize_filename(name):
    return name.lower().replace(" ", "_") + ".jpg"

def download_image(character):
    print(f"🔍 Searching for {character}...")
    params = {
        "engine": "google_images",
        "q": f"{character} Game of Thrones portrait",
        "api_key": API_KEY
    }
    try:
        search = GoogleSearch(params)
        results = search.get_dict()
        if "images_results" in results and results["images_results"]:
            image_url = results["images_results"][0]["original"]
            filename = sanitize_filename(character)
            filepath = os.path.join(output_dir, filename)
            urllib.request.urlretrieve(image_url, filepath)
            print(f"✅ Downloaded: {filename}")
        else:
            print(f"❌ No image found for {character}")
    except Exception as e:
        print(f"❌ Error downloading {character}: {e}")

for char in characters:
    download_image(char)

print("\n🎉 Done! All character portraits saved to /images")



